### PR TITLE
Update GPU-Viewer to 3.02

### PR DESCRIPTION
**Pull request by TingPing**

### CODE REVIEW

**Comment by TingPing** [comment]
The URL the data-checker creates seems invalid...

**Comment by arunsivaramanneo** [comment]
> The URL the data-checker creates seems invalid...

Hi .. I will see what i can do .. I am really bad at this .,... please let me know what i need to update .. .. just to let you know this update needs libadwaita version 1.4 or higher .. right now it only works on Ubuntu 23.10 and 24.04 so Gnome 45 or higher

**Comment by TingPing** [comment]
line 4 has `runtime-version: '44'` which you can change to `45`.

line 25/26 have the wrong URL.

It is generated by the `x-checker-data` below, which is documented here: https://github.com/flathub-infra/flatpak-external-data-checker

However you can deal with that later after the update.

**Comment by arunsivaramanneo** [comment]
I see the latest build failed due to developer name

 using PTY: False
{
    "errors": [
        "appstream-missing-developer-name"
    ],
    "warnings": [
        "appstream-summary-too-long",
        "appstream-screenshot-missing-caption"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
program finished with exit code 1
elapsedTime=0.882973

**Comment by TingPing** [comment]
@arunsivaramanneo Yes you need to update your appdata file.

Also please stop opening PRs, just reuse the same one.

**Pull request closed without merging**
