### PR TITLE
Upgrade runtime to gnome 44. Renew Finish-args. Update: GPU-Viewer 2.…

### PR DESCRIPTION
**Pull request by winehub**
Long time no see. Here a little bit of maintain:

Flatpak runtime gnome: 44
Update finish-args,
GPU-Viewer 2.29
VulkanTools 1.3.254
Vulkan-Headers 1.3.254
OpenCL-Headers 2023.04.17
pyobject 3.44.1
pycairo 1.24.0
orchis-theme 2023-05-27

mesa-demos x-data check has removed for now, because mesa-demos 9.0 isn't in the right position (root node).

### CODE REVIEW

**Comment by arunsivaramanneo** [comment]
Thanks , Its working now but i need to release a fix for Vulkan tools version 1.3.254, can you package this with Vulkan Tools version 1.3.250 for now. Also , you can remove ORchis Theme from dependency. thank you

**Comment by arunsivaramanneo** [comment]
Thank you .. this looks fine .. glxinfo is not present which i think is expected as mesa-demos being removed.

**Comment by winehub** [comment]
> Thank you .. this looks fine .. glxinfo is not present which i think is expected as mesa-demos being removed.

no there are in with 8.5:

flatpak run --command=/bin/sh io.github.arunsivaramanneo.GPUViewer 
[📦 io.github.arunsivaramanneo.GPUViewer ~]$ which glxinfo
/app/bin/glxinfo
glxinfo | grep ^OpenGL
OpenGL vendor string: AMD
.
.
.

**Comment by arunsivaramanneo** [comment]
Ah Ok .. Not sure why i am not able to see the OpenGL section 

Screenshot from 2023-06-21 15-41-36

**Comment by winehub** [comment]
> Ah Ok .. Not sure why i am not able to see the OpenGL section
> 
> Screenshot from 2023-06-21 15-41-36

here is mine at it works... I talk at this moment with org.freedesktop guys, because of missing vdpau. Manual fixed in the screenshot.

**Comment by arunsivaramanneo** [comment]
Great .. thanks .. This works fine .. will you be able publish the application .. thanks you so much

**Comment by winehub** [comment]
@tinywrkb  can merge thouse changes?

**Comment by arunsivaramanneo** [comment]
@TingPing @tinywrkb could you please help when you get time to publish the latest version.. thanks

**Comment by arunsivaramanneo** [comment]
@tinywrkb Can you help with the merge

**Comment by andypiper** [comment]
Not sure how this gets "promoted" on Flathub to be the version that is being distributed... I am still seeing v2.26 with the GNOME 43 runtime as the available version.

**Comment by TingPing** [comment]
@andypiper The build failed, I triggered a new one.

**Pull request merged**
