### PR TITLE
Update to 2.24

### PR DESCRIPTION
**Pull request by tinywrkb**
Supersedes #58

### CODE REVIEW

**Comment by tinywrkb** [comment]
Merging even though I really don't like that we now default to a dark theme, and not able to override it without going into the trouble of setting an env var.

**Comment by arunsivaramanneo** [comment]
> Merging even though I really don't like that we now default to a dark theme, and not able to override it without going into the trouble of setting an env var.

Not a fan of Dark theme ?? I thought most of them wanted a dark theme :(  .. I will work on having an option to chose Dark or Light theme in coming Release .. might take time .. thanks a lot

**Comment by tinywrkb** [comment]
IMO, apps should default to follow the Freedesktop color-scheme key, which is the system current color scheme.  
I've looked at the docs, but I wouldn't be surprised if you get that for free with GTK, meaning no extra code.  
The option to manually select a different color scheme will need some work, but you should be able to find some examples.  
From a UI design perspective, I really like how [Text Editor](https://flathub.org/apps/details/org.gnome.TextEditor) handles this.

**Comment by arunsivaramanneo** [comment]
> IMO, apps should default to follow the Freedesktop color-scheme key, which is the system current color scheme. I've not looked at the docs, but I wouldn't be surprised if you get that for free with GTK, meaning no extra code. The option to manually select a different color scheme will need some work, but you should be able to find some examples. From a UI design perspective, I really like how [Text Editor](https://flathub.org/apps/details/org.gnome.TextEditor) handles this.

I got your point .... Let me see how i can do this .. I am still discovering Gtk4 day by day .. hopefully i will find out how i can do this .. thanks .. atleast i know where i can start ...

**Comment by arunsivaramanneo** [comment]
Looks like it didn't deploy this time as well ..

**Comment by tinywrkb** [comment]
No, it's fine. [The MetaInfo file is missing an entry for 2.24](https://github.com/arunsivaramanneo/GPU-Viewer/blob/v2.24/data/io.github.arunsivaramanneo.GPUViewer.metainfo.xml#L33).

```
flatpak info io.github.arunsivaramanneo.GPUViewer

GPU-Viewer - A front-end to glxinfo, vulkaninfo, clinfo and es2_info

          ID: io.github.arunsivaramanneo.GPUViewer
         Ref: app/io.github.arunsivaramanneo.GPUViewer/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.22
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 23.4 MB
     Runtime: org.gnome.Platform/x86_64/43
         Sdk: org.gnome.Sdk/x86_64/43

      Commit: 67a1ce40e34de047dd83e64a9d067d3d00117ea61249c6feeac5521728d8a159
      Parent: 1e82b31d91cddb7d948043ec707d4980e5ecc1d18a65deb9936a2f709278442c
     Subject: vulkan-headers/tools: Update to 1.3.240 (d7d1c6e9)
        Date: 2023-02-12 19:21:38 +0000
```

Notice the `Subject` line

```
     Subject: vulkan-headers/tools: Update to 1.3.240 (d7d1c6e9)
```

and [the latest merge commit](https://github.com/flathub/io.github.arunsivaramanneo.GPUViewer/commit/d7d1c6e96fa9cf68b3ec72259fe975c660d666bb).

**Pull request merged**
